// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourDeFrance.Data;

#nullable disable

namespace TourDeFrance.Data.Migrations
{
    [DbContext(typeof(TourDeFranceDbContext))]
    [Migration("20260603150039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TourDeFrance.Data.Entities.Deelnemer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deelnemers");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.DeelnemerSelectie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeelnemerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RennerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volgorde")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RennerId");

                    b.HasIndex("DeelnemerId", "RennerId")
                        .IsUnique();

                    b.ToTable("DeelnemerSelecties");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.EindKlassement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AKPositie")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BergPositie")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PuntenPositie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RennerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RennerId")
                        .IsUnique();

                    b.ToTable("EindKlassementen");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Etappe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Afstand")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("EindLocatie")
                        .HasColumnType("TEXT");

                    b.Property<int>("EtappeNummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EtappeType")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartLocatie")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Etappes");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.EtappeUitslag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtappeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Positie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RennerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RennerId");

                    b.HasIndex("EtappeId", "RennerId")
                        .IsUnique();

                    b.ToTable("EtappeUitslagen");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Ploeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Land")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ploegen");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Renner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Land")
                        .HasColumnType("TEXT");

                    b.Property<int>("PloegId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Startnummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PloegId");

                    b.HasIndex("Startnummer")
                        .IsUnique();

                    b.ToTable("Renners");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.DeelnemerSelectie", b =>
                {
                    b.HasOne("TourDeFrance.Data.Entities.Deelnemer", "Deelnemer")
                        .WithMany("Selecties")
                        .HasForeignKey("DeelnemerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourDeFrance.Data.Entities.Renner", "Renner")
                        .WithMany("Selecties")
                        .HasForeignKey("RennerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deelnemer");

                    b.Navigation("Renner");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.EindKlassement", b =>
                {
                    b.HasOne("TourDeFrance.Data.Entities.Renner", "Renner")
                        .WithOne("EindKlassement")
                        .HasForeignKey("TourDeFrance.Data.Entities.EindKlassement", "RennerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Renner");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.EtappeUitslag", b =>
                {
                    b.HasOne("TourDeFrance.Data.Entities.Etappe", "Etappe")
                        .WithMany("Uitslagen")
                        .HasForeignKey("EtappeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourDeFrance.Data.Entities.Renner", "Renner")
                        .WithMany("EtappeUitslagen")
                        .HasForeignKey("RennerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etappe");

                    b.Navigation("Renner");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Renner", b =>
                {
                    b.HasOne("TourDeFrance.Data.Entities.Ploeg", "Ploeg")
                        .WithMany("Renners")
                        .HasForeignKey("PloegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ploeg");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Deelnemer", b =>
                {
                    b.Navigation("Selecties");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Etappe", b =>
                {
                    b.Navigation("Uitslagen");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Ploeg", b =>
                {
                    b.Navigation("Renners");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Renner", b =>
                {
                    b.Navigation("EindKlassement");

                    b.Navigation("EtappeUitslagen");

                    b.Navigation("Selecties");
                });
#pragma warning restore 612, 618
        }
    }
}
