// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TourDeFrance.Data;

#nullable disable

namespace TourDeFrance.Data.Migrations.SqlServer
{
    [DbContext(typeof(TourDeFranceDbContext))]
    partial class TourDeFranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TourDeFrance.Data.Entities.Deelnemer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deelnemers");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.DeelnemerSelectie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeelnemerId")
                        .HasColumnType("int");

                    b.Property<int>("RennerId")
                        .HasColumnType("int");

                    b.Property<int>("Volgorde")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RennerId");

                    b.HasIndex("DeelnemerId", "RennerId")
                        .IsUnique();

                    b.ToTable("DeelnemerSelecties");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.EindKlassement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AKPositie")
                        .HasColumnType("int");

                    b.Property<int?>("BergPositie")
                        .HasColumnType("int");

                    b.Property<int?>("PuntenPositie")
                        .HasColumnType("int");

                    b.Property<int>("RennerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RennerId")
                        .IsUnique();

                    b.ToTable("EindKlassementen");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Etappe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Afstand")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateOnly?>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("EindLocatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EtappeNummer")
                        .HasColumnType("int");

                    b.Property<string>("EtappeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartLocatie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Etappes");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.EtappeUitslag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EtappeId")
                        .HasColumnType("int");

                    b.Property<int>("Positie")
                        .HasColumnType("int");

                    b.Property<int>("RennerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RennerId");

                    b.HasIndex("EtappeId", "RennerId")
                        .IsUnique();

                    b.ToTable("EtappeUitslagen");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Ploeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Land")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ploegen");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Renner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Land")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PloegId")
                        .HasColumnType("int");

                    b.Property<int>("Startnummer")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PloegId");

                    b.HasIndex("Startnummer")
                        .IsUnique();

                    b.ToTable("Renners");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.DeelnemerSelectie", b =>
                {
                    b.HasOne("TourDeFrance.Data.Entities.Deelnemer", "Deelnemer")
                        .WithMany("Selecties")
                        .HasForeignKey("DeelnemerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourDeFrance.Data.Entities.Renner", "Renner")
                        .WithMany("Selecties")
                        .HasForeignKey("RennerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deelnemer");
                    b.Navigation("Renner");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.EindKlassement", b =>
                {
                    b.HasOne("TourDeFrance.Data.Entities.Renner", "Renner")
                        .WithOne("EindKlassement")
                        .HasForeignKey("TourDeFrance.Data.Entities.EindKlassement", "RennerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Renner");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.EtappeUitslag", b =>
                {
                    b.HasOne("TourDeFrance.Data.Entities.Etappe", "Etappe")
                        .WithMany("Uitslagen")
                        .HasForeignKey("EtappeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourDeFrance.Data.Entities.Renner", "Renner")
                        .WithMany("EtappeUitslagen")
                        .HasForeignKey("RennerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etappe");
                    b.Navigation("Renner");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Renner", b =>
                {
                    b.HasOne("TourDeFrance.Data.Entities.Ploeg", "Ploeg")
                        .WithMany("Renners")
                        .HasForeignKey("PloegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ploeg");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Deelnemer", b =>
                {
                    b.Navigation("Selecties");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Etappe", b =>
                {
                    b.Navigation("Uitslagen");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Ploeg", b =>
                {
                    b.Navigation("Renners");
                });

            modelBuilder.Entity("TourDeFrance.Data.Entities.Renner", b =>
                {
                    b.Navigation("EindKlassement");
                    b.Navigation("EtappeUitslagen");
                    b.Navigation("Selecties");
                });
#pragma warning restore 612, 618
        }
    }
}
